name: build_action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      
      - name: Build Docker Image
        run: |
          image_name="${{ secrets.USERNAME }}/netwiki"
          tag_name="${{secrets.IMAGETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo docker build -t $image_name:$tag_name -f ${{ secrets.DOCKERFILE }} .

      - name: Build and push ALI
        id: ALI_build
        run: |
          image_name="${{ secrets.USERNAME }}/netwiki"
          tag_name="${{secrets.IMAGETAG}}"
          sudo docker tag  $image_name:latest registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name
          sudo docker push registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      - name: check container
        run: |
          container_name="netwiki"
          tag_name="${{secrets.IMAGETAG}}"
          if docker ps -a | grep $container_name > /dev/null ; then
            echo "Docker container already exists, removing..."        
            docker stop $container_name
            docker rm $container_name
          fi
      - name: Pull ALI Image
        run: |
          image_name="${{ secrets.ALIREPOSITORY }}"
          tag_name="${{secrets.IMAGETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo  docker pull ${{ secrets.ALIREPOSITORY }}:$tag_name
      
      - name: Run Docker container
        run: |
          container_name="netwiki"
          tag_name="${{secrets.IMAGETAG}}"
          sudo docker run --name $container_name -p ${{secrets.PORT}}:80 -d ${{ secrets.ALIREPOSITORY }}:$tag_name
